-- MySQL Script generated by MySQL Workbench
-- Tue Apr 12 18:49:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cmspf_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_USERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(250) NULL,
  `lastname` VARCHAR(250) NULL,
  `pwd` VARCHAR(60) NOT NULL,
  `pwd1` VARCHAR(60) NULL,
  `pwd2` VARCHAR(60) NULL,
  `rank` INT NOT NULL,
  `mail` VARCHAR(250) NOT NULL,
  `phone` CHAR(10) NULL,
  `deleted` INT NULL,
  `confirm` INT NULL,
  `token` VARCHAR(60) NULL,
  `date_update_pwd` DATE NULL,
  `date_creation` DATE NULL DEFAULT 'CURRENT_TIMESTAMP',
  `date_update` DATE NULL,
  `tries` INT NULL,
  `2FAToken` VARCHAR(60) NULL,
  `2FAKey` CHAR(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_RESEAUX_SOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_RESEAUX_SOC` (
  `id` INT NOT NULL,
  `type` INT NOT NULL,
  `path` VARCHAR(250) NULL,
  `reseaux_soc_user_key` INT NOT NULL,
  PRIMARY KEY (`id`, `reseaux_soc_user_key`),
  INDEX `fk_cmspf_RESEAUX_SOC_cmspf_USERS1_idx` (`reseaux_soc_user_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_RESEAUX_SOC_cmspf_USERS1`
    FOREIGN KEY (`reseaux_soc_user_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_PAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_PAGES` (
  `id` INT NOT NULL,
  `title` VARCHAR(60) NULL,
  `description` VARCHAR(250) NULL,
  `date_update` DATE NULL,
  `page_user_key` INT NOT NULL,
  PRIMARY KEY (`id`, `page_user_key`),
  INDEX `fk_cmspf_NEWSLETTERS_cmspf_USERS1_idx` (`page_user_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_NEWSLETTERS_cmspf_USERS1`
    FOREIGN KEY (`page_user_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_STATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_STATS` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `country` CHAR(2) NULL,
  `reseau_soc_stat_key` INT NOT NULL,
  `page_stat_key` INT NOT NULL,
  PRIMARY KEY (`id`, `reseau_soc_stat_key`, `page_stat_key`),
  INDEX `fk_cmspf_STATS_cmspf_RESEAUX_SOC1_idx` (`reseau_soc_stat_key` ASC) VISIBLE,
  INDEX `fk_cmspf_STATS_cmspf_PAGES1_idx` (`page_stat_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_STATS_cmspf_RESEAUX_SOC1`
    FOREIGN KEY (`reseau_soc_stat_key`)
    REFERENCES `mydb`.`cmspf_RESEAUX_SOC` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_STATS_cmspf_PAGES1`
    FOREIGN KEY (`page_stat_key`)
    REFERENCES `mydb`.`cmspf_PAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_OPTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_OPTIONS` (
  `id` INT NOT NULL,
  `type` INT NOT NULL,
  `path` VARCHAR(250) NULL,
  `value` VARCHAR(20) NULL,
  `option_user_key` INT NOT NULL,
  PRIMARY KEY (`id`, `option_user_key`),
  INDEX `fk_cmspf_OPTIONS_cmspf_USERS_idx` (`option_user_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_OPTIONS_cmspf_USERS`
    FOREIGN KEY (`option_user_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_PROJETS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_PROJETS` (
  `id` INT NOT NULL,
  `title` VARCHAR(250) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_STEPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_STEPS` (
  `id` INT NOT NULL,
  `title` VARCHAR(250) NULL,
  `description` TEXT NULL,
  `date` DATE NULL,
  `projet_step_key` INT NOT NULL,
  `step_user_key` INT NOT NULL,
  PRIMARY KEY (`id`, `projet_step_key`, `step_user_key`),
  INDEX `fk_cmspf_STEPS_cmspf_PROJETS1_idx` (`projet_step_key` ASC) VISIBLE,
  INDEX `fk_cmspf_STEPS_cmspf_USERS1_idx` (`step_user_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_STEPS_cmspf_PROJETS1`
    FOREIGN KEY (`projet_step_key`)
    REFERENCES `mydb`.`cmspf_PROJETS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_STEPS_cmspf_USERS1`
    FOREIGN KEY (`step_user_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_USER_PROJET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_USER_PROJET` (
  `id` INT NOT NULL,
  `editor_user_projet_key` INT NOT NULL,
  `conserned_user_projet_key` INT NOT NULL,
  `projet_user_key` INT NOT NULL,
  PRIMARY KEY (`id`, `editor_user_projet_key`, `conserned_user_projet_key`, `projet_user_key`),
  INDEX `fk_cmspf_USER_PROJET_cmspf_USERS1_idx` (`editor_user_projet_key` ASC) VISIBLE,
  INDEX `fk_cmspf_USER_PROJET_cmspf_USERS2_idx` (`conserned_user_projet_key` ASC) VISIBLE,
  INDEX `fk_cmspf_USER_PROJET_cmspf_PROJETS1_idx` (`projet_user_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_USER_PROJET_cmspf_USERS1`
    FOREIGN KEY (`editor_user_projet_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_USER_PROJET_cmspf_USERS2`
    FOREIGN KEY (`conserned_user_projet_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_USER_PROJET_cmspf_PROJETS1`
    FOREIGN KEY (`projet_user_key`)
    REFERENCES `mydb`.`cmspf_PROJETS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_RDVS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_RDVS` (
  `id` INT NOT NULL,
  `title` VARCHAR(140) NULL,
  `date` DATE NULL,
  `status` INT NULL,
  `location` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `rdv_step_key` INT NOT NULL,
  PRIMARY KEY (`id`, `rdv_step_key`),
  INDEX `fk_cmspf_RDVS_cmspf_STEPS1_idx` (`rdv_step_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_RDVS_cmspf_STEPS1`
    FOREIGN KEY (`rdv_step_key`)
    REFERENCES `mydb`.`cmspf_STEPS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_USER_RDV_ASSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_USER_RDV_ASSO` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `user_rdv_key` INT NOT NULL,
  `rdv_user_key` INT NOT NULL,
  PRIMARY KEY (`id`, `user_rdv_key`, `rdv_user_key`),
  INDEX `fk_cmspf_USER_RDV_ASSO_cmspf_USERS1_idx` (`user_rdv_key` ASC) VISIBLE,
  INDEX `fk_cmspf_USER_RDV_ASSO_cmspf_RDVS1_idx` (`rdv_user_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_USER_RDV_ASSO_cmspf_USERS1`
    FOREIGN KEY (`user_rdv_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_USER_RDV_ASSO_cmspf_RDVS1`
    FOREIGN KEY (`rdv_user_key`)
    REFERENCES `mydb`.`cmspf_RDVS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_MESSAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_MESSAGES` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `publish` INT NULL,
  `content` TEXT NULL,
  `type` INT NULL,
  `description` TEXT NULL,
  `message_user_key` INT NOT NULL,
  `destination_message_user_key` INT NOT NULL,
  `message_step_key` INT NOT NULL,
  PRIMARY KEY (`id`, `message_user_key`, `destination_message_user_key`, `message_step_key`),
  INDEX `fk_cmspf_MESSAGES_cmspf_USERS1_idx` (`message_user_key` ASC) VISIBLE,
  INDEX `fk_cmspf_MESSAGES_cmspf_USERS2_idx` (`destination_message_user_key` ASC) VISIBLE,
  INDEX `fk_cmspf_MESSAGES_cmspf_STEPS1_idx` (`message_step_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_MESSAGES_cmspf_USERS1`
    FOREIGN KEY (`message_user_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_MESSAGES_cmspf_USERS2`
    FOREIGN KEY (`destination_message_user_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_MESSAGES_cmspf_STEPS1`
    FOREIGN KEY (`message_step_key`)
    REFERENCES `mydb`.`cmspf_STEPS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_SECTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_SECTIONS` (
  `id` INT NOT NULL,
  `witdth` INT NULL,
  `background` CHAR(6) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_NEWSLETTERS_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_NEWSLETTERS_copy1` (
  `id` INT NOT NULL,
  `title` VARCHAR(60) NULL,
  `date_update` DATE NULL,
  `date_release` DATE NULL,
  `newsletter_user_key` INT NOT NULL,
  `newsletter_section_key` INT NOT NULL,
  PRIMARY KEY (`id`, `newsletter_user_key`, `newsletter_section_key`),
  INDEX `fk_cmspf_NEWSLETTERS_cmspf_USERS1_idx` (`newsletter_user_key` ASC) VISIBLE,
  INDEX `fk_cmspf_NEWSLETTERS_copy1_cmspf_SECTIONS1_idx` (`newsletter_section_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_NEWSLETTERS_cmspf_USERS10`
    FOREIGN KEY (`newsletter_user_key`)
    REFERENCES `mydb`.`cmspf_USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_NEWSLETTERS_copy1_cmspf_SECTIONS1`
    FOREIGN KEY (`newsletter_section_key`)
    REFERENCES `mydb`.`cmspf_SECTIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_SECTION_SECTION_ASSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_SECTION_SECTION_ASSO` (
  `id` INT NOT NULL,
  `id_section_parent` INT NOT NULL,
  `id_section_child` INT NOT NULL,
  PRIMARY KEY (`id`, `id_section_parent`, `id_section_child`),
  INDEX `fk_cmspf_SECTION_SECTION_ASSO_cmspf_SECTIONS1_idx` (`id_section_parent` ASC) VISIBLE,
  INDEX `fk_cmspf_SECTION_SECTION_ASSO_cmspf_SECTIONS2_idx` (`id_section_child` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_SECTION_SECTION_ASSO_cmspf_SECTIONS1`
    FOREIGN KEY (`id_section_parent`)
    REFERENCES `mydb`.`cmspf_SECTIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_SECTION_SECTION_ASSO_cmspf_SECTIONS2`
    FOREIGN KEY (`id_section_child`)
    REFERENCES `mydb`.`cmspf_SECTIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_PAGE_SECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_PAGE_SECTION` (
  `id` INT NOT NULL,
  `id_page` INT NOT NULL,
  `id_section` INT NOT NULL,
  PRIMARY KEY (`id`, `id_page`, `id_section`),
  INDEX `fk_cmspf_PAGE_SECTION_cmspf_PAGES1_idx` (`id_page` ASC) VISIBLE,
  INDEX `fk_cmspf_PAGE_SECTION_cmspf_SECTIONS1_idx` (`id_section` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_PAGE_SECTION_cmspf_PAGES1`
    FOREIGN KEY (`id_page`)
    REFERENCES `mydb`.`cmspf_PAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_PAGE_SECTION_cmspf_SECTIONS1`
    FOREIGN KEY (`id_section`)
    REFERENCES `mydb`.`cmspf_SECTIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_SITE_ELEMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_SITE_ELEMENTS` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `witdth` INT NULL,
  `description` VARCHAR(250) NULL,
  `cmspf_SITE_ELEMENTScol1` VARCHAR(45) NULL,
  `cmspf_SITE_ELEMENTScol` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `font` CHAR(6) NULL,
  `color` CHAR(6) NULL,
  `background` CHAR(6) NULL,
  `font_size` INT NULL,
  `h_align` INT NULL,
  `section_site_element_key` INT NOT NULL,
  PRIMARY KEY (`id`, `section_site_element_key`),
  INDEX `fk_cmspf_SITE_ELEMENTS_cmspf_SECTIONS1_idx` (`section_site_element_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_SITE_ELEMENTS_cmspf_SECTIONS1`
    FOREIGN KEY (`section_site_element_key`)
    REFERENCES `mydb`.`cmspf_SECTIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_LANGUAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_LANGUAGES` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `flag` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_TRANSLATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_TRANSLATIONS` (
  `id` INT NOT NULL,
  `content` TEXT NULL,
  `language_translate_key` INT NOT NULL,
  PRIMARY KEY (`id`, `language_translate_key`),
  INDEX `fk_cmspf_TRANSLATIONS_cmspf_LANGUAGES1_idx` (`language_translate_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_TRANSLATIONS_cmspf_LANGUAGES1`
    FOREIGN KEY (`language_translate_key`)
    REFERENCES `mydb`.`cmspf_LANGUAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_CATEGORIES` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `title` VARCHAR(30) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_PAGE_CATEGORIE_ASSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_PAGE_CATEGORIE_ASSO` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `page_key` INT NOT NULL,
  `categorie_key` INT NOT NULL,
  PRIMARY KEY (`id`, `page_key`, `categorie_key`),
  INDEX `fk_cmspf_PAGE_CATEGORIE_ASSO_cmspf_PAGES1_idx` (`page_key` ASC) VISIBLE,
  INDEX `fk_cmspf_PAGE_CATEGORIE_ASSO_cmspf_CATEGORIES1_idx` (`categorie_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_PAGE_CATEGORIE_ASSO_cmspf_PAGES1`
    FOREIGN KEY (`page_key`)
    REFERENCES `mydb`.`cmspf_PAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_PAGE_CATEGORIE_ASSO_cmspf_CATEGORIES1`
    FOREIGN KEY (`categorie_key`)
    REFERENCES `mydb`.`cmspf_CATEGORIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_CATEGORIE_CATEGORIE_ASSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_CATEGORIE_CATEGORIE_ASSO` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `categorie_parent_key` INT NOT NULL,
  `categorie_child_key` INT NOT NULL,
  PRIMARY KEY (`id`, `categorie_parent_key`, `categorie_child_key`),
  INDEX `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_cmspf_CATEGORIES1_idx` (`categorie_parent_key` ASC) VISIBLE,
  INDEX `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_cmspf_CATEGORIES2_idx` (`categorie_child_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_cmspf_CATEGORIES1`
    FOREIGN KEY (`categorie_parent_key`)
    REFERENCES `mydb`.`cmspf_CATEGORIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_cmspf_CATEGORIES2`
    FOREIGN KEY (`categorie_child_key`)
    REFERENCES `mydb`.`cmspf_CATEGORIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_PAGE_TRANSLATION_ASSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_PAGE_TRANSLATION_ASSO` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `cmspf_PAGE_TRANSLATION_ASSOcol` VARCHAR(45) NULL,
  `translate_key` INT NOT NULL,
  `page_key` INT NOT NULL,
  PRIMARY KEY (`id`, `translate_key`, `page_key`),
  INDEX `fk_cmspf_PAGE_TRANSLATION_ASSO_cmspf_TRANSLATIONS1_idx` (`translate_key` ASC) VISIBLE,
  INDEX `fk_cmspf_PAGE_TRANSLATION_ASSO_cmspf_PAGES1_idx` (`page_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_PAGE_TRANSLATION_ASSO_cmspf_TRANSLATIONS1`
    FOREIGN KEY (`translate_key`)
    REFERENCES `mydb`.`cmspf_TRANSLATIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_PAGE_TRANSLATION_ASSO_cmspf_PAGES1`
    FOREIGN KEY (`page_key`)
    REFERENCES `mydb`.`cmspf_PAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_CATEGORIE_TRANSLATION_ASSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_CATEGORIE_TRANSLATION_ASSO` (
  `id` INT NOT NULL,
  `translate_key` INT NOT NULL,
  `categorie_key` INT NOT NULL,
  PRIMARY KEY (`id`, `translate_key`, `categorie_key`),
  INDEX `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_copy1_copy1_cmspf_TRANSLA_idx` (`translate_key` ASC) VISIBLE,
  INDEX `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_copy1_copy1_cmspf_CATEGOR_idx` (`categorie_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_copy1_copy1_cmspf_TRANSLATI1`
    FOREIGN KEY (`translate_key`)
    REFERENCES `mydb`.`cmspf_TRANSLATIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_CATEGORIE_CATEGORIE_ASSO_copy1_copy1_cmspf_CATEGORIES1`
    FOREIGN KEY (`categorie_key`)
    REFERENCES `mydb`.`cmspf_CATEGORIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cmspf_SITE_ELEMENT_TRANSLATION_ASSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cmspf_SITE_ELEMENT_TRANSLATION_ASSO` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `site_element_translate_key` INT NOT NULL,
  `translate_site_element_key` INT NOT NULL,
  PRIMARY KEY (`id`, `site_element_translate_key`, `translate_site_element_key`),
  INDEX `fk_cmspf_SITE_ELEMENT_TRANSLATION_ASSO_cmspf_SITE_ELEMENTS1_idx` (`site_element_translate_key` ASC) VISIBLE,
  INDEX `fk_cmspf_SITE_ELEMENT_TRANSLATION_ASSO_cmspf_TRANSLATIONS1_idx` (`translate_site_element_key` ASC) VISIBLE,
  CONSTRAINT `fk_cmspf_SITE_ELEMENT_TRANSLATION_ASSO_cmspf_SITE_ELEMENTS1`
    FOREIGN KEY (`site_element_translate_key`)
    REFERENCES `mydb`.`cmspf_SITE_ELEMENTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmspf_SITE_ELEMENT_TRANSLATION_ASSO_cmspf_TRANSLATIONS1`
    FOREIGN KEY (`translate_site_element_key`)
    REFERENCES `mydb`.`cmspf_TRANSLATIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
