/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout
  middleware: ['auth']

/register:
  controller: user
  action: register

/dashboard:
  controller: statistics
  action: loadDashboard
  middleware: [ 'auth', 'admin' ]

/userdelete:
  controller: user
  action: deleteUser
  params: [id]
  middleware: [ 'auth', 'admin' ]

/updaterank:
  controller: user
  action: updateRank
  params: [id]
  middleware: [ 'auth', 'admin' ]

/pageloader:
  controller: pageengine
  action: pageLoader
  params: [ slug ]

/pages:
  controller: pageengine
  action: listPage
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/build:
  controller: pageengine
  action: buildPage
  params: [ slug ]
  middleware: [ 'auth', 'admin' ]

/build/save:
  controller: pageengine
  action: saveContentPage
  middleware : ['auth', 'admin']

/page/compose:
  controller: pageengine
  action: composePage
  params: [id]
  middleware : ['auth', 'admin']

/page/delete:
  controller: pageengine
  action: deletePage
  middleware: [ 'auth', 'admin' ]

/add-code:
  controller: pageengine
  action: listAddCode
  middleware: [ 'auth', 'admin' ]

/add-code/compose:
  controller: pageengine
  action: composeAddCode
  middleware: [ 'auth', 'admin' ]

/categorie/compose:
  controller: categorie
  action: composeCategorie
  params: [id]
  middleware : ['auth', 'admin']

/categorie/delete:
  controller: categorie
  action: categorieDelete
  middleware: [ 'auth', 'admin' ]

/categories:
  controller: categorie
  action: categoriesList
  middleware: [ 'auth', 'admin' ]

/navigations:
  controller: categorie
  action: navigationsList
  middleware: [ 'auth', 'admin' ]

/settings/style:
  controller: option
  action: loadOption
  middleware : ['auth', 'admin']

/settings/user-manager:
  controller: settings
  action: listUser
  middleware : ['auth', 'admin']

/settings/configuration:
  controller: settings
  action: loadDatabase
  middleware : ['auth', 'admin']

/settings/database/compose:
  controller: settings
  action: composeDatabase
  middleware : ['auth', 'admin']

/settings/media-library:
  controller: settings
  action: listMedia
  middleware : ['auth', 'admin']

/sitemap:
  controller: pageengine
  action: siteMap


/conversations:
  controller: communication
  action: listConversation
  middleware : ['auth']

/conversation/compose:
  controller: communication
  action: composeConversation
  middleware : ['auth', 'admin']

/conversation/delete:
  controller: communication
  action: deleteConversation
  middleware: [ 'auth', 'admin' ]

/projects:
  controller: communication
  action: listProject
  middleware : ['auth']

/project/compose:
  controller: project
  action: composeProject
  middleware : ['auth', 'admin']

/project/delete:
  controller: project
  action: deleteProject
  middleware: [ 'auth', 'admin' ]

/step/compose:
  controller: project
  action: composeStep
  middleware : ['auth', 'admin']

/step/delete:
  controller: project
  action: deleteStep
  middleware: [ 'auth', 'admin' ]

/meetings:
  controller: meeting
  action: listRdv
  middleware : ['auth']

/load/slots:
  controller: meeting
  action: loadslot
  middleware : ['auth']

/load/meetings:
  controller: meeting
  action: loadMeetings
  middleware : ['auth']

/load/availablemeetings:
  controller: meeting
  action: loadAvailableMeetings
  middleware : ['auth']

/meeting/compose:
  controller: meeting
  action: composeMeeting
  middleware: ['auth']

/slots:
  controller: meeting
  action: listSlot
  middleware : ['auth', 'admin']

/slot/compose:
  controller: meeting
  action: composeSlot
  middleware: ['auth', 'admin']

/meeting/delete:
  controller: meeting
  action: deleteRdv
  middleware : ['auth']

/slot/delete:
  controller: meeting
  action: deleteRdv
  middleware : ['auth', 'admin']

/option/compose:
  controller: option
  action: composeOption
  middleware: ['auth', 'admin']

/social-media/compose:
  controller: statistics
  action: composereseauxsoc
  middleware : ['auth', 'admin']

/social-media/delete:
  controller: statistics
  action: deletereseauxsoc
  middleware : ['auth', 'admin']

/mailconfirmation:
  controller: user
  action: confirmMail
  params: [token]

/pwdforgotten:
  controller: user
  action: pwdReset

/resetpassword:
  controller: user
  action: newPwd
  params: [token]






