/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout
  middleware: ['auth']

/register:
  controller: user
  action: register

/dashboard:
  controller: statistics
  action: loadDashboard
  middleware: [ 'auth', 'admin' ]

/userdelete:
  controller: user
  action: deleteUser
  params: [id]
  middleware: [ 'auth', 'admin' ]

/updaterank:
  controller: user
  action: updateRank
  params: [id]
  middleware: [ 'auth', 'admin' ]

/pageloader:
  controller: pageengine
  action: pageLoader
  params: [ slug ]

/pages:
  controller: pageengine
  action: listPage
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/build:
  controller: pageengine
  action: buildPage
  params: [ slug ]
  middleware: [ 'auth', 'admin' ]

/build/save:
  controller: pageengine
  action: saveContentPage
  middleware : ['auth', 'admin']

/page/compose:
  controller: pageengine
  action: composePage
  params: [id]
  middleware : ['auth', 'admin']

/page/delete:
  controller: pageengine
  action: deletePage
  middleware: [ 'auth', 'admin' ]

/add-code:
  controller: pageengine
  action: listAddCode
  middleware: [ 'auth', 'admin' ]

/add-code/compose:
  controller: pageengine
  action: composeAddCode
  middleware: [ 'auth', 'admin' ]

/categorie/compose:
  controller: categorie
  action: composeCategorie
  params: [id]
  middleware : ['auth', 'admin']

/categorie/delete:
  controller: categorie
  action: categorieDelete
  middleware: [ 'auth', 'admin' ]

/categories:
  controller: categorie
  action: categoriesList
  middleware: [ 'auth', 'admin' ]

/navigation/page/compose:
  controller: categorie
  action: composeNavigationPage
  middleware: [ 'auth', 'admin' ]

/navigation/categorie/compose:
  controller: categorie
  action: composeNavigationCategorie
  middleware: [ 'auth', 'admin' ]

/navigation/option/compose:
  controller: categorie
  action: composeNavigationOption
  middleware: [ 'auth', 'admin' ]

/navigation/page/delete:
  controller: categorie
  action: deleteNavigationPage
  middleware: [ 'auth', 'admin' ]

/navigation/categorie/delete:
  controller: categorie
  action: deleteNavigationCategorie
  middleware: [ 'auth', 'admin' ]

/navigations:
  controller: categorie
  action: navigationsList
  middleware: [ 'auth', 'admin' ]

/settings/style:
  controller: option
  action: loadOption
  middleware : ['auth', 'admin']

/settings/user-manager:
  controller: settings
  action: listUser
  middleware : ['auth', 'admin']

/settings/configuration:
  controller: settings
  action: loadDatabase
  middleware : ['auth', 'admin']

/settings/database/compose:
  controller: settings
  action: composeDatabase
  middleware : ['auth', 'admin']

/settings/media-library:
  controller: option
  action: listImages
  middleware : ['auth', 'admin']

/sitemap:
  controller: pageengine
  action: siteMap

/conversations:
  controller: communication
  action: listConversation
  middleware : ['auth']

/conversations/search-conversations:
  controller: communication
  action: searchData
  middleware : ['auth']

/conversations/user-conversations:
  controller: communication
  action: userConversation
  params: [id_conv]
  middleware: [ 'auth', 'admin' ]

/conversations/get-all-messages:
  controller: communication
  action: messages
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/conversation/compose:
  controller: communication
  action: composeConversation
  middleware : ['auth', 'admin']

/conversation/compose-newconversation:
  controller: communication
  action: newConversation
  middleware : ['auth', 'admin']

/conversations/updateseen:
  controller: communication
  action: updateSeenStatus
  middleware : ['auth', 'admin']

/conversations/newmessage:
  controller: communication
  action: newMessage
  middleware : ['auth', 'admin']

/conversation/delete:
  controller: communication
  action: newMessage
  middleware: [ 'auth', 'admin' ]

/projects:
  controller: communication
  action: listProject
  middleware : ['auth']

/project/compose:
  controller: communication
  action: composeProject
  middleware : ['auth', 'admin']
  params: [title]

/project/delete:
  controller: communication
  action: deleteProject
  middleware: [ 'auth', 'admin' ]

/project:
  controller: communication
  action: loadProject
  middleware: [ 'auth' ]

/step/compose:
  controller: communication
  action: composeStep
  middleware : ['auth', 'admin']

/step/delete:
  controller: communication
  action: deleteStep
  middleware: [ 'auth', 'admin' ]

/meetings:
  controller: meeting
  action: listRdv
  middleware : ['auth']

/load/slots:
  controller: meeting
  action: loadslot
  middleware : ['auth']

/load/meetings:
  controller: meeting
  action: loadMeetings
  middleware : ['auth']

/load/availablemeetings:
  controller: meeting
  action: loadAvailableMeetings
  middleware : ['auth']

/meeting/compose:
  controller: meeting
  action: composeMeeting
  middleware: ['auth']

/slots:
  controller: meeting
  action: listSlot
  middleware : ['auth', 'admin']

/slot/compose:
  controller: meeting
  action: composeSlot
  middleware: ['auth', 'admin']

/meeting/delete:
  controller: meeting
  action: deleteRdv
  middleware : ['auth']

/slot/delete:
  controller: meeting
  action: deleteRdv
  middleware : ['auth', 'admin']

/option/compose:
  controller: option
  action: composeOption
  middleware: ['auth', 'admin']

/option/delete:
  controller: option
  action: deleteOption
  middleware: ['auth', 'admin']

/img/compose:
  controller: option
  action: composeImg
  middleware: ['auth', 'admin']

/img/delete:
  controller: option
  action: deleteOption
  middleware: ['auth', 'admin']

/social-media/compose:
  controller: statistics
  action: composereseauxsoc
  middleware : ['auth', 'admin']

/social-media/stat/compose:
  controller: statistics
  action: composestatreseauxsoc
  middleware : ['auth', 'admin']

/social-media/delete:
  controller: statistics
  action: deletereseauxsoc
  middleware : ['auth', 'admin']

/mailconfirmation:
  controller: user
  action: confirmMail
  params: [token]

/pwdforgotten:
  controller: user
  action: pwdReset

/resetpassword:
  controller: user
  action: newPwd
  params: [token]

/searchUser:
  controller: User
  action: findUsers
  params: [str]


/setup/database:
  controller: Setup
  action: loadDatabase

/setup/smtp:
  controller: Setup
  action: loadSmtp

/setup/login:
  controller: Setup
  action: loadLogin

/setup/main-images:
  controller: Setup
  action: loadMainImages
  middleware: [ 'auth', 'admin' ]

/setup/main-colors:
  controller: Setup
  action: loadMainColors
  middleware: [ 'auth', 'admin' ]

/setup/design/1:
  controller: Setup
  action: loadDesignFirst
  middleware: [ 'auth', 'admin' ]

/setup/design/2:
  controller: Setup
  action: loadDesignSecond
  middleware: [ 'auth', 'admin' ]

/newsletters:
  controller: newsletterengine
  action: listnewsletter
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/newsletter/build:
  controller: newsletterengine
  action: buildnewsletter
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/newsletter/build/save:
  controller: newsletterengine
  action: saveContentnewsletter
  middleware : ['auth', 'admin']

/newsletter/compose:
  controller: newsletterengine
  action: composenewsletter
  params: [id]
  middleware : ['auth', 'admin']

/newsletter/delete:
  controller: newsletterengine
  action: deletenewsletter
  middleware: [ 'auth', 'admin' ]






