admin/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: dashboard

/integration:
  controller: general
  action: integration

/mailconfirmation:
  controller: user
  action: mailconfirmation

/users_list:
  controller: user
  action: usersList

/rdv_calendar:
  controller: rendezvous
  action: calendar
  midleware: ['auth']


/rdv_calendar_insert:
  controller: rendezvous
  action: insertRdv

/calendar_load:
  controller: rendezvous
  action: load

/calendar_delete:
  controller: rendezvous
  action: deleteEvent

/rdv_calendar_update:
  controller: rendezvous
  action: updateEvent

/public_rdvs_list:
  controller: rendezvous
  action: public_rdvs_List

/public_rdvs_reserver:
  controller: rendezvous
  action: public_rdvs_reserver
  params: [id]

/user_delete/id:
  controller: user
  action: deleteUser

/page/compose:
  controller: pageengine
  action: composepage

/page/:
  controller: pageengine
  action: buildpage

/categorie/compose:
  controller: categorie
  action: composeCategorie
  params: [id]
  midleware : ['auth', 'admin']

/categorie/delete:
  controller: categorie
  action: categoriedelete
  params: [ id ]
  midleware: [ 'auth', 'admin' ]

/categories:
  controller: categorie
  action: categoriesList
  params: [ id ]
  midleware: [ 'auth', 'admin' ]
