admin/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout
  middleware: ['auth']

/register:
  controller: user
  action: register

/dashboard:
  controller: statistics
  action: loadDashboard

/userManagement:
  controller: admin
  action: userManagement

/integration:
  controller: general
  action: integration

/mailconfirmation:
  controller: user
  action: mailconfirmation

/users_list:
  controller: user
  action: usersList

/rdv_calendar:
  controller: rendezvous
  action: calendar
  middleware: ['auth']


/rdv_calendar_insert:
  controller: rendezvous
  action: insertRdv

/calendar_load:
  controller: rendezvous
  action: load
  middleware: ['auth']

/calendar_delete:
  controller: rendezvous
  action: deleteEvent

/rdv_calendar_update:
  controller: rendezvous
  action: updateEvent

/public_rdvs_list:
  controller: rendezvous
  action: public_rdvs_List

/public_rdvs_reserver:
  controller: rendezvous
  action: public_rdvs_reserver
  params: [id]
  middleware : ['auth']


/user_delete/id:
  controller: user
  action: deleteUser


/pageloader:
  controller: pageengine
  action: pageLoader
  params: [ slug ]

/pages:
  controller: pageengine
  action: listPage
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/build:
  controller: pageengine
  action: buildPage
  params: [ slug ]

/build/save:
  controller: pageengine
  action: saveContentPage
  middleware : ['auth', 'admin']

/page/compose:
  controller: pageengine
  action: composePage
  params: [id]
  middleware : ['auth', 'admin']

/page/delete:
  controller: pageengine
  action: deletePage
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/add-code:
  controller: pageengine
  action: listAddCode
  middleware: [ 'auth', 'admin' ]

/categorie/compose:
  controller: categorie
  action: composeCategorie
  params: [id]
  middleware : ['auth', 'admin']

/categorie/delete:
  controller: categorie
  action: categoriedelete
  params: [ id ]
  middleware: [ 'auth', 'admin' ]

/categories:
  controller: categorie
  action: categoriesList
  middleware: [ 'auth', 'admin' ]

/navigations:
  controller: categorie
  action: navigationsList
  middleware: [ 'auth', 'admin' ]
