/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register


/dashboard:
  controller: admin
  action: dashboard