/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: dashboard

/integration:
  controller: general
  action: integration

/mailconfirmation:
  controller: user
  action: mailconfirmation

/users_list:
  controller: user
  action: usersList

/rdv_calendar:
  controller: rendezvous
  action: calendar

/rdv_calendar_insert:
  controller: rendezvous
  action: insertRdv

/calendar_load:
  controller: rendezvous
  action: load

/calendar_delete:
  controller: rendezvous
  action: deleteEvent

/rdv_calendar_update:
  controller: rendezvous
  action: updateEvent